spring.application.name=EmployeeManagement_Logging
spring.datasource.url=jdbc:mysql://localhost:3306/logging_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging Level
logging.level.root=INFO
logging.level.com.logging=DEBUG

# Log File
logging.file.name=logs/application.log